language: python
sudo: required
group: deprecated-2017Q4
env:
  - PYTHON_VERSION=3.5 COVER_PACKAGE="qp_shogun/filter qp_shogun/trim qp_shogun/shogun"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -f -b -p $PWD/miniconda3
  - export PATH=$PWD/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing qiita environment
  - conda create --yes -n qiita python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1' matplotlib
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme
  - pip install https://github.com/biocore/qiita/archive/dev.zip --process-dependency-links
  - sed 's/PORT = 7777/PORT = 6379/g' ${PWD}/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - sed "s#/home/travis#${PWD}#g" config_test.cfg > config_test_local.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test_local.cfg
  - export QIITA_SERVER_CERT=${PWD}/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing qp-shogun
  - conda create --yes -n qp-shogun python=$PYTHON_VERSION pip nose flake8
  - source activate qp-shogun
  - pip install -U pip
  - conda install --yes pigz
  - conda install --yes -c bioconda bowtie2 fastqc=0.11.5 samtools bedtools
  - pip install sphinx sphinx-bootstrap-theme nose-timer codecov biopython
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install atropos
  - pip install git+https://github.com/knights-lab/SHOGUN.git
  - export QIITA_SERVER_CERT=$PWD/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  # just making sure we have the latest flake8
  - pip install -U flake8
  - pip install .
  - export QC_FILTER_DB_DP=$PWD/qp_shogun/filter/databases/
  - export QC_SHOGUN_DB_DP=$PWD/qp_shogun/shogun/databases/
  - for file in $(ls $QC_SHOGUN_DB_DP); do tar xvjf $QC_SHOGUN_DB_DP$file -C $QC_SHOGUN_DB_DP; done
  # installing other dependencies
  - wget --quiet https://bitbucket.org/biobakery/metaphlan2/get/default.zip
  - unzip -qq default.zip 'biobakery-metaphlan2*/utils/*' 'biobakery-metaphlan2*/metaphlan2.py'
  - wget --quiet https://github.com/biocore/oecophylla/blob/dev/test_data/test_dbs/mp2_mini.tar.gz?raw=true -O mp2_mini.tar.gz
  - tar zxf mp2_mini.tar.gz
  - wget https://github.com/knights-lab/UTree/releases/download/v2.0c/utree-search_gg
  - chmod 755 utree-search_gg
  - mv utree-search_gg $CONDA_PREFIX/bin
  - wget https://github.com/knights-lab/BURST/releases/download/v0.99.7f/burst_linux_DB12
  - chmod 755 burst_linux_DB12
  - mv burst_linux_DB12 $CONDA_PREFIX/bin/burst15
before_script:
  - source activate qiita
  - qiita pet webserver start &
  - export QIITA_PID=$!
script:
  - source activate qp-shogun
  - sleep 10 # give enough time to the webserver to start
  - configure_shogun --env-script "source activate qp-shogun" --server-cert $QIITA_SERVER_CERT
  - travis_wait 40 nosetests $COVER_PACKAGE --with-doctest --with-coverage --with-timer -vv --cover-package=$COVER_PACKAGE
  - flake8 qp_shogun setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - codecov
  - qiita-env drop
after_failure:
  - kill $QIITA_PID
  - qiita-env drop
