dist: xenial
language: python
sudo: false
env:
  - PYTHON_VERSION=3.6 COVER_PACKAGE="qp_shogun/filter qp_shogun/trim qp_shogun/shogun qp_shogun/sortmerna"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing qiita environment
  - conda config --add channels anaconda
  - travis_retry conda create -q --yes -n qiita python=3.6 pip libgfortran numpy nginx cython
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/dev.zip --no-binary redbiom
  - sed 's/PORT = 7777/PORT = 6379/g' ${HOME}/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  # starting nginx
  - mkdir /home/travis/miniconda3/envs/qiita/var/run/nginx/
  - wget https://github.com/biocore/qiita/archive/dev.zip -O qiita-dev.zip
  - unzip qiita-dev.zip
  - nginx -c ${PWD}/qiita-dev/qiita_pet/nginx_example.conf
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing qp-shogun
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda create --yes -n qp-shogun -c knights-lab shogun=1.0.7 biom-format samtools bedtools pigz sortmerna=2.1b
  - source activate qp-shogun
  - pip install -U pip pip nose flake8
  - pip install sphinx sphinx-bootstrap-theme nose-timer codecov biopython
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install atropos
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/server.crt
  - pip install .
  - export QC_FILTER_DB_DP=$PWD/qp_shogun/filter/databases/
  - export QC_SHOGUN_DB_DP=$PWD/qp_shogun/shogun/databases/
  - export QC_SORTMERNA_DB_DP=$PWD/qp_shogun/sortmerna/databases/
  - for file in $(ls $QC_SHOGUN_DB_DP); do tar xvjf $QC_SHOGUN_DB_DP$file -C $QC_SHOGUN_DB_DP; done
  - for file in $(ls $QC_SORTMERNA_DB_DP); do tar xvjf $QC_SORTMERNA_DB_DP$file -C $QC_SORTMERNA_DB_DP; done
  # shogun is currently installing an old version of burst so let's install the correct one
  - wget https://github.com/knights-lab/BURST/releases/download/v0.99.8/burst_linux_DB15
  - chmod 755 burst_linux_DB15
  - mv burst_linux_DB15 $CONDA_PREFIX/bin/burst15
  # making sure we have the correct software versions
  - shogun_version=`shogun --version`
  - bowtie2_version=`bowtie2 --version`
  - burst15_version=`burst15 -h | grep BURST`
  - utree_version=`(utree-search_gg || true)`
  - if [[ $shogun_version != *"1.0.7"* ]]; then echo "wrong shogun version", $shogun_version; exit 1; fi
  - if [[ $bowtie2_version != *"2.3.5"* ]]; then echo "wrong bowtie2 version", $bowtie2_version; exit 1; fi
  - if [[ $burst15_version != *"0.99.8"* ]]; then echo "wrong burst15 version", $burst15_version; exit 1; fi
  - if [[ $utree_version != *"2.0RF"* ]]; then echo "wrong utree version", $utree_version; exit 1; fi
  - configure_shogun --env-script "source activate qp-shogun" --server-cert $QIITA_SERVER_CERT
before_script:
  - source activate qiita
  - qiita plugins update
  - supervisord -c ${PWD}/qiita-dev/qiita_pet/supervisor_example.conf
  - sleep 10 # give enough time to the webserver to start
  - cat /tmp/supervisord.log
script:
  - source activate qp-shogun
  - travis_wait 40 nosetests $COVER_PACKAGE --with-doctest --with-coverage --with-timer -vv --cover-package=$COVER_PACKAGE
  - flake8 qp_shogun setup.py scripts
addons:
  postgresql: "9.5"
services:
  - redis-server
  - postgresql
after_success:
  - codecov
  - qiita-env drop
after_failure:
  - kill $QIITA_PID
  - qiita-env drop
